cc_library(
    name = "vm",
    srcs = ["vm.cc", "token.cc", "object.cc", "scanner.cc", "string.cc"],
    hdrs = ["vm.h", "token.h", "object.h", "scanner.h", "string.h"],
    visibility = ["//:__pkg__"]
)
